XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX XX
   XXXXXXXXXXXXXXXXX XX XXX XXX XX XXXXXXXX XXXXX
   XXX XXX XXXXX XXXX XXXX XXXXXXXXXX XX XXXX XXXXXXX XXX XX XXXXXX XX XXXXX
   XXXXXXX XXX XXXX XXXXXXXXX XXXXXXXXXX

XXXXXXX XX XXXXXXXXXXXX XXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XX XXXXXXXXX
   XXXXXXXXXX X
   XXXXXXXXX XXXXXXXXX



XXXXXXX XXX XXXXXX
XXXXXXXXXXXXXXXXXX

X XXXXXXXXXXXXXXX
X XXXXXXXXXXXXXXX
X XXXXXXXXXXXXX
